@CoffeeTunes.WebApi_HostAddress = http://localhost:5031

GET {{CoffeeTunes.WebApi_HostAddress}}/weatherforecast/
Accept: application/json

###

POST {{keycloak_base}}/realms/{{realm}}/protocol/openid-connect/token
Content-Type: application/x-www-form-urlencoded

grant_type=password&client_id={{client_id}}&username={{username}}&password={{password}}
