// <auto-generated />
using System;
using CoffeeTunes.WebApi.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CoffeeTunes.WebApi.Migrations
{
    [DbContext(typeof(CoffeeTunesDbContext))]
    [Migration("20251102095550_AddClubNameIndex")]
    partial class AddClubNameIndex
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CoffeeTunes.WebApi.Entities.Bar", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsOpen")
                        .HasColumnType("boolean");

                    b.Property<string>("Topic")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Bars");
                });

            modelBuilder.Entity("CoffeeTunes.WebApi.Entities.Bean", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CastFromId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CastToId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("IngredientId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CastFromId");

                    b.HasIndex("CastToId");

                    b.HasIndex("IngredientId");

                    b.ToTable("Beans");
                });

            modelBuilder.Entity("CoffeeTunes.WebApi.Entities.Club", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Clubs");
                });

            modelBuilder.Entity("CoffeeTunes.WebApi.Entities.Hipster", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Hipsters");
                });

            modelBuilder.Entity("CoffeeTunes.WebApi.Entities.HipstersInClub", b =>
                {
                    b.Property<Guid>("ClubId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("HipsterId")
                        .HasColumnType("uuid");

                    b.HasKey("ClubId", "HipsterId");

                    b.HasIndex("HipsterId");

                    b.ToTable("HipstersInClubs");
                });

            modelBuilder.Entity("CoffeeTunes.WebApi.Entities.Ingredient", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Used")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("Ingredients");
                });

            modelBuilder.Entity("CoffeeTunes.WebApi.Entities.Bean", b =>
                {
                    b.HasOne("CoffeeTunes.WebApi.Entities.Hipster", "CastTo")
                        .WithMany()
                        .HasForeignKey("CastFromId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CoffeeTunes.WebApi.Entities.Hipster", "CastFrom")
                        .WithMany()
                        .HasForeignKey("CastToId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CoffeeTunes.WebApi.Entities.Ingredient", "Ingredient")
                        .WithMany("Beans")
                        .HasForeignKey("IngredientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CastFrom");

                    b.Navigation("CastTo");

                    b.Navigation("Ingredient");
                });

            modelBuilder.Entity("CoffeeTunes.WebApi.Entities.HipstersInClub", b =>
                {
                    b.HasOne("CoffeeTunes.WebApi.Entities.Club", "Club")
                        .WithMany("HipstersInClubs")
                        .HasForeignKey("ClubId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CoffeeTunes.WebApi.Entities.Hipster", "Hipster")
                        .WithMany()
                        .HasForeignKey("HipsterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Club");

                    b.Navigation("Hipster");
                });

            modelBuilder.Entity("CoffeeTunes.WebApi.Entities.Club", b =>
                {
                    b.Navigation("HipstersInClubs");
                });

            modelBuilder.Entity("CoffeeTunes.WebApi.Entities.Ingredient", b =>
                {
                    b.Navigation("Beans");
                });
#pragma warning restore 612, 618
        }
    }
}
