// <auto-generated />
using System;
using CoffeeTunes.WebApi.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CoffeeTunes.WebApi.Migrations
{
    [DbContext(typeof(CoffeeTunesDbContext))]
    partial class CoffeeTunesDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CoffeeTunes.WebApi.Entities.Bar", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("FranchiseId")
                        .HasColumnType("uuid");

                    b.Property<bool>("HasSupplyLeft")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsOpen")
                        .HasColumnType("boolean");

                    b.Property<long>("MaxIngredientsPerHipster")
                        .HasColumnType("bigint");

                    b.Property<string>("Topic")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("FranchiseId");

                    b.ToTable("Bars");
                });

            modelBuilder.Entity("CoffeeTunes.WebApi.Entities.BarHipsterStatistics", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("BarId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("BarStatisticsId")
                        .HasColumnType("uuid");

                    b.Property<int>("CorrectGuesses")
                        .HasColumnType("integer");

                    b.Property<Guid>("HipsterId")
                        .HasColumnType("uuid");

                    b.Property<int>("IngredientsSubmitted")
                        .HasColumnType("integer");

                    b.Property<int>("TotalGuesses")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("BarId");

                    b.HasIndex("BarStatisticsId");

                    b.HasIndex("HipsterId");

                    b.ToTable("BarHipsterStatistics");
                });

            modelBuilder.Entity("CoffeeTunes.WebApi.Entities.BarStatistics", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("BarId")
                        .HasColumnType("uuid");

                    b.Property<int>("BeansCastCount")
                        .HasColumnType("integer");

                    b.Property<int>("CorrectCastsCount")
                        .HasColumnType("integer");

                    b.Property<Guid>("FranchiseId")
                        .HasColumnType("uuid");

                    b.Property<int>("IngredientsBrewedCount")
                        .HasColumnType("integer");

                    b.Property<int>("TotalHipstersContributedCount")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("BarId");

                    b.HasIndex("FranchiseId");

                    b.ToTable("BarStatistics");
                });

            modelBuilder.Entity("CoffeeTunes.WebApi.Entities.Bean", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CastFromId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CastToId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("IngredientId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("CastFromId");

                    b.HasIndex("CastToId");

                    b.HasIndex("IngredientId");

                    b.ToTable("Beans");
                });

            modelBuilder.Entity("CoffeeTunes.WebApi.Entities.Franchise", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Franchises");
                });

            modelBuilder.Entity("CoffeeTunes.WebApi.Entities.Hipster", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Hipsters");
                });

            modelBuilder.Entity("CoffeeTunes.WebApi.Entities.HipstersCastIngredientBean", b =>
                {
                    b.Property<Guid>("HipsterId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("IngredientId")
                        .HasColumnType("uuid");

                    b.HasKey("HipsterId", "IngredientId");

                    b.HasIndex("IngredientId");

                    b.ToTable("HipstersCastIngredientBeans");
                });

            modelBuilder.Entity("CoffeeTunes.WebApi.Entities.HipstersInFranchise", b =>
                {
                    b.Property<Guid>("FranchiseId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("HipsterId")
                        .HasColumnType("uuid");

                    b.HasKey("FranchiseId", "HipsterId");

                    b.HasIndex("HipsterId");

                    b.ToTable("HipstersInFranchises");
                });

            modelBuilder.Entity("CoffeeTunes.WebApi.Entities.HipstersSubmittedIngredient", b =>
                {
                    b.Property<Guid>("HipsterId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("IngredientId")
                        .HasColumnType("uuid");

                    b.HasKey("HipsterId", "IngredientId");

                    b.HasIndex("IngredientId");

                    b.ToTable("HipstersSubmittedIngredients");
                });

            modelBuilder.Entity("CoffeeTunes.WebApi.Entities.Ingredient", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("BarId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Revealed")
                        .HasColumnType("boolean");

                    b.Property<bool>("Selected")
                        .HasColumnType("boolean");

                    b.Property<string>("ThumbnailUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Used")
                        .HasColumnType("boolean");

                    b.Property<string>("VideoId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("BarId");

                    b.ToTable("Ingredients");
                });

            modelBuilder.Entity("CoffeeTunes.WebApi.Entities.Bar", b =>
                {
                    b.HasOne("CoffeeTunes.WebApi.Entities.Franchise", "Franchise")
                        .WithMany()
                        .HasForeignKey("FranchiseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Franchise");
                });

            modelBuilder.Entity("CoffeeTunes.WebApi.Entities.BarHipsterStatistics", b =>
                {
                    b.HasOne("CoffeeTunes.WebApi.Entities.Bar", "Bar")
                        .WithMany()
                        .HasForeignKey("BarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CoffeeTunes.WebApi.Entities.BarStatistics", "BarStatistics")
                        .WithMany("BarHipsterStatistics")
                        .HasForeignKey("BarStatisticsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CoffeeTunes.WebApi.Entities.Hipster", "Hipster")
                        .WithMany()
                        .HasForeignKey("HipsterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bar");

                    b.Navigation("BarStatistics");

                    b.Navigation("Hipster");
                });

            modelBuilder.Entity("CoffeeTunes.WebApi.Entities.BarStatistics", b =>
                {
                    b.HasOne("CoffeeTunes.WebApi.Entities.Bar", "Bar")
                        .WithMany()
                        .HasForeignKey("BarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CoffeeTunes.WebApi.Entities.Franchise", "Franchise")
                        .WithMany()
                        .HasForeignKey("FranchiseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bar");

                    b.Navigation("Franchise");
                });

            modelBuilder.Entity("CoffeeTunes.WebApi.Entities.Bean", b =>
                {
                    b.HasOne("CoffeeTunes.WebApi.Entities.Hipster", "CastFrom")
                        .WithMany()
                        .HasForeignKey("CastFromId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CoffeeTunes.WebApi.Entities.Hipster", "CastTo")
                        .WithMany()
                        .HasForeignKey("CastToId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CoffeeTunes.WebApi.Entities.Ingredient", "Ingredient")
                        .WithMany("Beans")
                        .HasForeignKey("IngredientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CastFrom");

                    b.Navigation("CastTo");

                    b.Navigation("Ingredient");
                });

            modelBuilder.Entity("CoffeeTunes.WebApi.Entities.HipstersCastIngredientBean", b =>
                {
                    b.HasOne("CoffeeTunes.WebApi.Entities.Hipster", "Hipster")
                        .WithMany()
                        .HasForeignKey("HipsterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CoffeeTunes.WebApi.Entities.Ingredient", "Ingredient")
                        .WithMany()
                        .HasForeignKey("IngredientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hipster");

                    b.Navigation("Ingredient");
                });

            modelBuilder.Entity("CoffeeTunes.WebApi.Entities.HipstersInFranchise", b =>
                {
                    b.HasOne("CoffeeTunes.WebApi.Entities.Franchise", "Franchise")
                        .WithMany("HipstersInFranchises")
                        .HasForeignKey("FranchiseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CoffeeTunes.WebApi.Entities.Hipster", "Hipster")
                        .WithMany()
                        .HasForeignKey("HipsterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Franchise");

                    b.Navigation("Hipster");
                });

            modelBuilder.Entity("CoffeeTunes.WebApi.Entities.HipstersSubmittedIngredient", b =>
                {
                    b.HasOne("CoffeeTunes.WebApi.Entities.Hipster", "Hipster")
                        .WithMany()
                        .HasForeignKey("HipsterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CoffeeTunes.WebApi.Entities.Ingredient", "Ingredient")
                        .WithMany("Owners")
                        .HasForeignKey("IngredientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hipster");

                    b.Navigation("Ingredient");
                });

            modelBuilder.Entity("CoffeeTunes.WebApi.Entities.Ingredient", b =>
                {
                    b.HasOne("CoffeeTunes.WebApi.Entities.Bar", "Bar")
                        .WithMany("Ingredients")
                        .HasForeignKey("BarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bar");
                });

            modelBuilder.Entity("CoffeeTunes.WebApi.Entities.Bar", b =>
                {
                    b.Navigation("Ingredients");
                });

            modelBuilder.Entity("CoffeeTunes.WebApi.Entities.BarStatistics", b =>
                {
                    b.Navigation("BarHipsterStatistics");
                });

            modelBuilder.Entity("CoffeeTunes.WebApi.Entities.Franchise", b =>
                {
                    b.Navigation("HipstersInFranchises");
                });

            modelBuilder.Entity("CoffeeTunes.WebApi.Entities.Ingredient", b =>
                {
                    b.Navigation("Beans");

                    b.Navigation("Owners");
                });
#pragma warning restore 612, 618
        }
    }
}
